In [1]:
l=[23245,27,546,215,-1234]

In [2]:
l

[23245, 27, 546, 215, -1234]

In [3]:
import numpy as np

In [5]:
a=np.array(l)

In [6]:
a

array([23245,    27,   546,   215, -1234])

In [7]:
b=np.array([12,455,63.3,True,'a'])

In [8]:
b

array(['12', '455', '63.3', 'True', 'a'], dtype='<U32')

In [9]:
print(b)

['12' '455' '63.3' 'True' 'a']


In [10]:
a.mean()

4559.8

-------------

In [11]:
a[2:]

array([  546,   215, -1234])

In [12]:
a[2:4]

array([546, 215])

In [13]:
b=a[2:4]#this is not creating a new array. just a view of array
#but lists  create a copy 

In [14]:
b[0]

546

In [15]:
b[:]=111

In [16]:
b

array([111, 111])

In [17]:
a

array([23245,    27,   111,   111, -1234])

In [18]:
c=a.copy()

In [19]:
c

array([23245,    27,   111,   111, -1234])

In [20]:
c[0]=0

In [21]:
c

array([    0,    27,   111,   111, -1234])

In [22]:
a

array([23245,    27,   111,   111, -1234])

In [23]:
l1 = [20, 'a', 21, 'b', 22, 'c', 23, 'd', 24, 'e', 25, 'f']



In [24]:
l1[-1:-12:-2]

['f', 'e', 'd', 'c', 'b', 'a']